In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# location to the true test counts - blockwise
csv_path = 'data/test_block_true_counts'

In [3]:
csv_contents = os.listdir(csv_path)

In [4]:
# remove the checkpointing folder
csv_contents = [file for file in csv_contents if file.split(".")[-1] == 'csv']

In [5]:
csv_contents.sort()
csv_contents

['block_0103_true_counts.csv',
 'block_0104_true_counts.csv',
 'block_0105_true_counts.csv',
 'block_0106_true_counts.csv',
 'block_0201_true_counts.csv',
 'block_0202_true_counts.csv',
 'block_0205_true_counts.csv',
 'block_0206_true_counts.csv',
 'block_0302_true_counts.csv',
 'block_0303_true_counts.csv',
 'block_0304_true_counts.csv',
 'block_0305_true_counts.csv',
 'block_0306_true_counts.csv']

In [6]:
def true_counts_from_df(file_path, file):
    df = pd.read_csv(os.path.join(file_path, file))
    # we only need the true counts for test data
    test_df = df.iloc[-7:, :]
    return test_df.values[:, -1]

In [7]:
# block 0103

In [8]:
# from previously stored
test_true_blk_0103 = true_counts_from_df(csv_path, csv_contents[0])

In [9]:
test_true_blk_0103

array([40.00066054548968, 39.00000127295261, 41.00000000000001,
       31.00000000000001, 31.99999951259551, 40.00208572484232,
       27.000175670785342], dtype=object)

In [10]:
# values copied from the inference scripts

In [11]:
# 0    40.000661
# 1    39.000002
# 2    41.000000
# 3    31.000000
# 4    32.000000
# 5    40.002086
# 6    27.000176

In [12]:
# values match

In [13]:
# block 0104

In [14]:
# from previously stored
test_true_blk_0104 = true_counts_from_df(csv_path, csv_contents[1])

In [15]:
test_true_blk_0104

array([32.999999999999986, 30.00000000000001, 39.00000127295262, 40.0,
       40.99881043962579, 42.169008804753545, 30.005316665182622],
      dtype=object)

In [16]:
# values copied from the inference scripts

In [17]:
# 0    33.000000
# 1    30.000000
# 2    39.000001
# 3    40.000000
# 4    40.998810
# 5    42.169009
# 6    30.005317

In [18]:
# values match

In [19]:
# block 0105

In [20]:
# from previously stored
test_true_blk_0105 = true_counts_from_df(csv_path, csv_contents[2])

In [21]:
test_true_blk_0105

array([40.0000012729526, 46.00274307612427, 58.00069611233912,
       41.00003199860504, 41.00118956037423, 36.00002186137552,
       23.000000487404503], dtype=object)

In [22]:
# values copied from the inference scripts

In [23]:
# 0    40.000001
# 1    46.002743
# 2    58.000696
# 3    41.000032
# 4    41.001190
# 5    36.000022
# 6    23.000001

In [24]:
# values match

In [25]:
# block 0106

In [26]:
# from previously stored
test_true_blk_0106 = true_counts_from_df(csv_path, csv_contents[3])

In [27]:
test_true_blk_0106

array([38.999666655123626, 38.9999891048778, 45.0, 39.98688726617951,
       42.99999680579228, 47.99650163259803, 38.00000000000001],
      dtype=object)

In [28]:
# values copied from the inference scripts

In [29]:
# 0    38.999667
# 1    38.999989
# 2    45.000000
# 3    39.986887
# 4    42.999997
# 5    47.996502
# 6    38.000000

In [30]:
# values match

In [31]:
# block 0201

In [32]:
# from previously stored
test_true_blk_0201 = true_counts_from_df(csv_path, csv_contents[4])

In [33]:
test_true_blk_0201

array([45.00021729155998, 45.00003969951952, 47.00000127295259,
       37.99999951259552, 42.00004097247213, 35.00000000000001,
       29.000000000000004], dtype=object)

In [34]:
# values copied from the inference scripts

In [35]:
# 0    45.000217
# 1    45.000040
# 2    47.000001
# 3    37.999999
# 4    42.000041
# 5    35.000000
# 6    29.000000

In [36]:
# values match

In [37]:
# block 0202

In [38]:
# from previously stored
test_true_blk_0202 = true_counts_from_df(csv_path, csv_contents[5])

In [39]:
test_true_blk_0202

array([17.9999603004805, 21.0, 22.999999512595508, 20.99998216185602,
       21.000000000000007, 18.000000000000004, 18.000000000000007],
      dtype=object)

In [40]:
# values copied from the inference scripts

In [41]:
# 0    17.999960
# 1    21.000000
# 2    23.000000
# 3    20.999982
# 4    21.000000
# 5    18.000000
# 6    18.000000

In [42]:
# values match

In [43]:
# block 0205

In [44]:
# from previously stored
test_true_blk_0205 = true_counts_from_df(csv_path, csv_contents[6])

In [45]:
test_true_blk_0205

array([44.000000000000014, 42.0000012729526, 44.99999999999998,
       43.00000000000001, 38.99999999999999, 40.99991511146148,
       31.999655760001424], dtype=object)

In [46]:
# values copied from the inference scripts

In [47]:
# 0    44.000000
# 1    42.000001
# 2    45.000000
# 3    43.000000
# 4    39.000000
# 5    40.999915
# 6    31.999656

In [48]:
# values match

In [49]:
# block 0206

In [50]:
# from previously stored
test_true_blk_0206 = true_counts_from_df(csv_path, csv_contents[7])

In [51]:
test_true_blk_0206

array([40.99983792383744, 41.99881043962578, 39.00006705039453,
       32.00000319420774, 25.00035194091306, 23.00003969951952,
       17.999999512595505], dtype=object)

In [52]:
# values copied from the inference scripts

In [53]:
# 0    40.999838
# 1    41.998811
# 2    39.000067
# 3    32.000003
# 4    25.000352
# 5    23.000040
# 6    18.000000

In [54]:
# values match

In [55]:
# block 0302

In [56]:
# from previously stored
test_true_blk_0302 = true_counts_from_df(csv_path, csv_contents[8])

In [57]:
test_true_blk_0302

array([49.0, 49.00000499411124, 53.99956959851029, 50.04234944329424,
       43.00000897386708, 48.00057246274347, 36.99999902519102],
      dtype=object)

In [58]:
# values copied from the inference scripts

In [59]:
# 0    49.000000
# 1    49.000005
# 2    53.999570
# 3    50.042349
# 4    43.000009
# 5    48.000573
# 6    36.999999

In [60]:
# values match

In [61]:
# block 0303

In [62]:
# from previously stored
test_true_blk_0303 = true_counts_from_df(csv_path, csv_contents[9])

In [63]:
test_true_blk_0303

array([49.00017120362504, 46.00000672610549, 42.999982161856025,
       38.99999312418006, 36.0258842391973, 36.0, 22.999999999999996],
      dtype=object)

In [64]:
# values copied from the inference scripts

In [65]:
# 0    49.000171
# 1    46.000007
# 2    42.999983
# 3    38.999993
# 4    36.025885
# 5    36.000000
# 6    23.000000

In [66]:
# values match

In [67]:
# block 0304

In [68]:
# from previously stored
test_true_blk_0304 = true_counts_from_df(csv_path, csv_contents[10])

In [69]:
test_true_blk_0304

array([37.000000000000014, 41.00205747505135, 42.99999807874491,
       41.999954810980974, 37.9999995125955, 34.00000000000002, 24.0],
      dtype=object)

In [70]:
# values copied from the inference scripts

In [71]:
# 0    37.000000
# 1    41.002058
# 2    42.999998
# 3    41.999955
# 4    37.999999
# 5    34.000000
# 6    24.000000

In [72]:
# values match

In [73]:
# block 0305

In [74]:
# from previously stored
test_true_blk_0305 = true_counts_from_df(csv_path, csv_contents[11])

In [75]:
test_true_blk_0305

array([45.99999999999999, 35.000000000000014, 37.00000000000001,
       30.000651571622612, 35.00118956037424, 28.999993572038143,
       20.00001783814397], dtype=object)

In [76]:
# values copied from the inference scripts

In [77]:
# 0    46.000000
# 1    35.000000
# 2    37.000000
# 3    30.000651
# 4    35.001190
# 5    28.999994
# 6    20.000018

In [78]:
# values match

In [79]:
# block 0306

In [80]:
# from previously stored
test_true_blk_0306 = true_counts_from_df(csv_path, csv_contents[12])

In [81]:
test_true_blk_0306

array([41.0000089738671, 41.00000319420772, 43.00685125110357,
       39.99760431406018, 40.0, 32.999982161856046, 18.0], dtype=object)

In [82]:
# values copied from the inference scripts

In [83]:
# 0    41.000009
# 1    41.000003
# 2    43.006851
# 3    39.997605
# 4    40.000000
# 5    32.999982
# 6    18.000000

In [84]:
# values match